package jpa_exercise.model;

import javax.persistence.*;

//TODO make the Address entity
//TODO map this class to table named ADDRESSES_EX
//TODO make the id field autogenerated from the database
//TODO map street to street_number column
@Entity
@Table(name="ADDRESSES_EX")
public class Address {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column
    private String street;

    @Column(name = "street_number")
    private int number;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("id: " + id);
        builder.append(", street name: " + street);
        builder.append(", street number: " + number);

        return builder.toString();
    }

}
