package jpa_exercise.model;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.List;

//TODO make the order entity
//TODO map this class to table named ORDERS_EX
//TODO make the id field autogenerated from the database
//TODO make the relationship with the products
//TODO make the relationship with the address
//TODO map orderDate to order_date column
@Entity
@Table(name="ORDERS_EX")
public class Order {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    @Column(name="order_date")
    private LocalDate orderDate;
    private Double price;

    @OneToOne
    @JoinColumn(name = "address_id", referencedColumnName = "id")
    private Address address;

    @OneToMany(fetch = FetchType.EAGER)
    @JoinColumn(name = "order_id")
    private List<Product> products;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LocalDate getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(LocalDate orderDate) {
        this.orderDate = orderDate;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("order id: "+id+" \n");
        builder.append("order date: "+orderDate+" \n");
        builder.append("price: "+price+" \n");
        builder.append("address: "+address+ " \n");
        builder.append("products: ");
        products.forEach( product ->
                builder.append(product.getName()+", ")
        );
        return builder.toString();

    }

}